feat: Выполнил задание 10 спринта, написал тесты и доп задачу.
prit4er/java-filmorate pull request #1
Opened 2024-11-18 15:17 UTC by prit4er

2024-11-18 17:31 UTC, prit4er commented
Не понимаю почему не работает:
public User create(@Valid @RequestBody User user)
И логику переменные приходится валидировать внутри метода, а не в модульном классе при наличии всех аннотаций

2024-11-18 17:32 UTC, prit4er commented
Вот в этом комите пытался
https://github.com/prit4er/java-filmorate/pull/1/commits/ca950a417856e8b73db8687ffdfa802d6dff028a

2024-11-18 19:05 UTC, tomattman requested changes
Привет работа хорошая, есть парочка вещей на испарвление
стоит удалить дефолтные значения где не надо и перепроверь правила валидации для пользователя, думаю что падают тесты именно из за них

2024-11-18 19:05 UTC, tomattman commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private static final Logger log = LoggerFactory.getLogger(FilmController.class);
у ломбука есть аннотация на класс, которая автоматически добавляет логгер в класс

2024-11-18 19:05 UTC, tomattman commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            return null;
обычно еси что то должно возвращать список, а значений для него не найдено, то возвращают пустой список, а если единичный обьект то ошибку со статусом 404

2024-11-18 19:05 UTC, tomattman commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (film.getId() == null || film.getId() <= 0) {
но отрицательные id вполне валидны

2024-11-18 19:05 UTC, tomattman commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        // Даже при наличии аннатаций внутри модульного класса,
было условие что если имя пустое, то в него надо просетать значение из логина

2024-11-18 19:05 UTC, tomattman commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private Long id = Long.valueOf(0);
зачем добавлять значение по умолчанию на генерируемое поле, ты не сможешь понять реальное это значение или значение сгенерированное по умолчанию, для таких полей дефолтное лучше null

2024-11-18 19:05 UTC, tomattman commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    @Builder.Default
и снова, добавляя значение по умолчанию там где не надо, ты получаешь потенцильные ошибки, стоит убрать все значения по умолчанию, тем более что этого нету в условии

2024-11-18 19:05 UTC, tomattman commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    @NotNull(message = "Имя не может быть null")
имя может быть null есил оно null то используется значение из логина

2024-11-18 19:05 UTC, tomattman commented on src/test/java/ru/yandex/practicum/filmorate/UserControllerTest.java
> +            assertEquals("Список юзеров пуст", e.getMessage());
интересно, но такие мелочи чаще всего не проверяют, только если есть конкретное требование, что такое сообщение должно прийти в определенном случае

2024-11-18 19:05 UTC, tomattman commented on src/test/java/ru/yandex/practicum/filmorate/UserTest.java
> +class UserTest {
валидация часть работы контрооллера, можно было бы тестировать и в тесте контроллера, но и так тоже можно (минус только в том, что некоторые валидации у тебя на уровне методов, и тут на них тестирования не будет)

2024-11-19 07:42 UTC, prit4er commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    @NotNull(message = "Имя не может быть null")
Вот в этом кстати и была ошибка)
Я убрал и валидация через аннотация нормально заработала в create методе, без доп проверок

2024-11-19 08:02 UTC, prit4er commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        // Даже при наличии аннатаций внутри модульного класса,
У меня внутри User класса обработка getName идет

    // Кастомная логика для установки имени по умолчанию как логин, если имя пустое
    public String getName() {
        if (name == null || name.isBlank()) {
            return login;  // Используем логин, если имя пустое
        }
        return name;
    }

2024-11-19 16:08 UTC, tomattman requested changes
еще есть парочка моментов

2024-11-19 16:08 UTC, tomattman commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        user.setId(getNextId());
вот тут надо просетать в имя значение из логина, если в логине ничего нету

2024-11-19 16:08 UTC, tomattman commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private String description = "Default description";
все еще есть дефолтные значение, которого тут не должно быть по условию

2024-11-19 16:08 UTC, tomattman commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private LocalDate releaseDate = LocalDate.of(2000, 12, 28);
и тут

2024-11-19 16:08 UTC, tomattman commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private Integer duration = Integer.valueOf(110);
и тут

2024-11-22 09:57 UTC, tomattman approved these changes
Принято, остались не критические мелочи

2024-11-22 09:57 UTC, tomattman commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        //Почему я не могу иметь эту валидацию в методе getName класса модели User?
потому что валидируем мы на уровне контроллера, и в него может прийти пустое значение, и это будет валидно, а уже где то ниже ниже можно просетать корректное значение

2024-11-22 09:57 UTC, tomattman commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +            return null;
я уже писал кажется, но если мы возвращаем список, и вернуть нечего, то стоит вернуть пустой список

2024-11-22 09:57 UTC, tomattman commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        users.put(newUser.getId(), newUser);
по хорошему тут тоже стоило бы обновить имя пользователя

2024-12-18 14:25 UTC, merged