Функциональность доработана для 11 спринта
prit4er/java-filmorate pull request #2
Opened 2024-12-21 00:58 UTC by prit4er

2024-12-21 03:46 UTC, prit4er commented
Нужна помощь, я максимально не понимаю, почему не работает один метод и тест не проходит у чекстайла
<img width="1137" alt="Снимок экрана 2024-12-21 в 06 46 16" src="https://github.com/user-attachments/assets/6010c0ab-9bf7-4116-838e-1354166df063" />

2024-12-21 12:50 UTC, tomattman requested changes
По поводу вопроса по ошибке
у меня нету постмановских тестов, но судя по ошибкам у тебя эндпоинт скорее всего падает на этом тесте с какой то шибкой, и следовательно не тот статус, не те поля в ответе, возможно хранилище не пустое, или наоборот учитывая что это Pit запрос, оно пустое а в нем должно быть какое то значение, плюс посмотри у тебя пара тестов на билде упало, если не получится понять попробуй мне в пачке прислать сам тест гляну что там может быть не так

2024-12-21 12:50 UTC, tomattman commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    @Autowired
можно вместо написания вручную конструкторов повесить аннотацию RequiredArgsConstructor с ней конструктор создастся автоматически

2024-12-21 12:50 UTC, tomattman commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    @ExceptionHandler
сейчас у етбя обработчики исключений будут в каждом классе контроллера, погугли аннотацию @ControllerAdvice с ней можно сделать класс обработчик исключений который будет работать сразу со всеми контроллерами

2024-12-21 12:50 UTC, tomattman commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Map<String, String> handleThrowable(final Throwable e) {
можно было бы создать класс специально для представления ответа на ошибку, например добавить ему поля тип ошибки, текст ошибки, потому что сейчас очень легко где то ошибиться и вставить не правильный ключ в мапу, и какая ни будь логика на фронтенде сломается

2024-12-21 12:50 UTC, tomattman commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private InMemoryUserStorage inMemoryUserStorage;
мы не работаем с хранилищем напрямую, все через сервис

2024-12-21 12:50 UTC, tomattman commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private InMemoryUserStorage inMemoryUserStorage;
ну и такие же комментарии как в контроллере фильмов

2024-12-21 12:50 UTC, tomattman commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +public class Film implements Comparable<Film> {
тут рекомендовал бы использовать не интерфейс comparable а comporaещк значит что ты будешь сравнивать всегда одинаково, а компараторов даже для фильма может быть множество под разные ситуации 
(это просто как рекомендация, текущий вариант тоже норм)

2024-12-21 12:50 UTC, tomattman commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    public void setToFriends(Long id) {
addToFriends
ну и вообще такие методы излишни, обычно хватает сеттера и на уровне сервиса делаем все то же user.getFriends().add(id);

2024-12-21 12:50 UTC, tomattman commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    public void setToFriends(Long id) {
то же и про фильмы и некоторые другие методы

2024-12-21 12:50 UTC, tomattman commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    private static final Logger log = LoggerFactory.getLogger(FilmController.class);
почему в фильм сервисе логгер на фильм контроллер?

2024-12-21 12:50 UTC, tomattman commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public FilmService(FilmStorage filmStorage, UserStorage inMemoryUserStorage) {
уже кажется писал коммент про RequiredArgsConstructor

2024-12-21 12:50 UTC, tomattman commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        return filmStorage.getFilmById(filmId);
Обычно с сервиса уже возвращают сам обьект т.е. на уровне сервиса получают optional сделают проверку и бросить ошибку

2024-12-21 12:50 UTC, tomattman commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public void giveLike(Long userId, Long filmId) {
give? может лучше add?

2024-12-21 12:50 UTC, tomattman commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        Optional<User> user = inMemoryUserStorage.getUserById(userId);
такие моменты чаще проверяют через orElseThrow
inMemoryUserStorage.getUserById(userId).orElseThrow(() -> new NotFoundException("Юзер с id " + userId + " отсутствует"))
а лучше сделать метод 
private User getUser(Long id) {
return inMemoryUserStorage.getUserById(userId).orElseThrow(() -> new NotFoundException("Юзер с id " + userId + " отсутствует"));
}
и если ты его просто вызовешь, он проверит наличие пользователя в базе, если нужен результат, то можешь записасть его в переменную

2024-12-21 12:50 UTC, tomattman commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        Optional<User> user = inMemoryUserStorage.getUserById(userId);
так же и с фильмами

2024-12-21 12:50 UTC, tomattman commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        List<Film> allFilmsList = new ArrayList<>(filmStorage.findAll());
лучше на урвоне репозитория сделать метод который будет возвращать нужное количество фильмов
представь что у тебя тысяча фильмов, а тебе надо вернуть 5 самых популярных и каждый раз ты будешь получать все 1000 чтобы забрать 5
(да пока ты работаешь с памятью, это почти не влияет, но когда с базой начнешь работать то будет заметнее)

2024-12-21 12:50 UTC, tomattman commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    private static final Logger log = LoggerFactory.getLogger(UserController.class);
аналогично как и с фильмами

2024-12-21 12:50 UTC, tomattman commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    private static final Logger log = LoggerFactory.getLogger(UserController.class);
думаю все комменты оттуда будут актуальны

2024-12-21 12:50 UTC, tomattman commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +    private static final Logger log = LoggerFactory.getLogger(FilmController.class);
почему везде логгер привязан к контроллеру?

2024-12-21 12:50 UTC, tomattman commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +        if (film.getName() == null || film.getName().isBlank()) {
валидация конечно может быть и здесь, но обычно ее делают на уровне контроллера аннотациями
а когда добавите базу, так ты проверить не сможешь, поэтому рекомендую переделать

вообще валидация это обычно уровень контроллера, ну или сервиса если надо проверить что то с комплексной логикой

2024-12-21 12:50 UTC, tomattman commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +        if (films.isEmpty()) {
можно сделать гораздо проще 
return Optional.ofNullable(films.get(id));
ну а логов на уровне сервиса хатит

2024-12-21 12:50 UTC, tomattman commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +public class InMemoryUserStorage implements UserStorage {
аналогично как с хранилищем фильмов

2024-12-22 07:03 UTC, prit4er commented
<img width="909" alt="Снимок экрана 2024-12-22 в 10 00 41" src="https://github.com/user-attachments/assets/a83b5e6c-70c8-4ef4-a421-5b887f480765" />
Что то поправить удалось, но проблемы с новыми методами, сейчас разбираюсь
Буду рад паре комментариев

2024-12-22 20:41 UTC, tomattman requested changes
чек стайл не прошел
плюс добавил еще парочку комментов, 
про постман тесты уже писал, у меня их нету, но если они в том виде в котором я к ним привык, то ты же можешь запустить конкретный тест и посмотреть почему он падает

2024-12-22 20:41 UTC, tomattman commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    private static final Logger log = LoggerFactory.getLogger(FilmController.class);
этот вопрос все еще актуален +  у ломбкуа есть аннотация Slf4j которая добавил логгер в класс автоматически в переменную log

2024-12-23 06:00 UTC, prit4er commented
Постман коллекция
https://github.com/yandex-praktikum/java-filmorate/blob/add-friends-likes/postman/sprint.json

2024-12-23 06:04 UTC, prit4er commented
Я вот вообще не понимаю что делать с Апи тестами, они просто не хотят никак работать
Написал тесты отдельно на лайки, и там все работает

Прямо сейчас максимально не понимаю, что делать с этим, у меня нет уже никакого понимания
я смотрел на чужой код, искал ответы, и всю ночь с этим провел

2024-12-23 06:43 UTC, prit4er commented
Буквально этот метод с PathVariable находит фильм по id
`    @GetMapping("/{filmId}")
    public Film getFilmById(@PathVariable Long filmId) {
        log.info("Запрос на получение фильма с id = {}", filmId);
        return filmService.getFilmById(filmId);
    }`
   
   А метод лайка уже не может и вечно выдает
   
   {
    "errorMessage": "Произошла ошибка: No static resource films/{{film_id}}/like/{{id}}"
}

2024-12-23 15:51 UTC, tomattman requested changes
для того чтобы принять работу, билд должен быть зеленым
Если что то не получается с ним, то можно спросить наставника

2024-12-23 16:25 UTC, prit4er commented
Ощущения, что нужно было добавить
@NoArgsConstructor
@AllArgsConstructor

в класс модели
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Film implements Comparable<Film> {

иначе он в попытке сбилдить лайки пытался обратиться к какому то конструктору которого нет и падал
    private Set<Long> likes = new HashSet<>();

2024-12-24 10:58 UTC, tomattman approved these changes
Принято

2024-12-25 05:33 UTC, merged